version: "3.8"
services:

  # Applications

  product-service:
    depends_on:
      - bookshop-postgres
    build:
      context: ./product-service
    image: product-service
    container_name: "product-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_product
      - SPRING_PROFILES_ACTIVE=testdata
  order-service:
    depends_on:
      - bookshop-postgres
      - bookshop-rabbitmq
    build:
      context: ./order-service
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - BOOKSHOP_PRODUCT_SERVICE_URI=http://product-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_order
      - SPRING_RABBITMQ_HOST=bookshop-rabbitmq
  dispatcher-service:
    depends_on:
      - bookshop-rabbitmq
    image: "dispatcher-service"
    container_name: dispatcher-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=bookshop-rabbitmq
  edge-service:
    depends_on:
      - bookshop-keycloak
      - bookshop-redis
      - bookshop-ui
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - SPA_URL=http://bookshop-ui:9004
      - PRODUCT_SERVICE_URL=http://product-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=bookshop-redis
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/bookshop
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  bookshop-ui:
    image: "bookshop-ui"
    container_name: "bookshop-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004
  # Backing Services

  bookshop-postgres:
    image: "postgres:14.12"
    container_name: "bookshop-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql


  bookshop-redis:
    image: "redis:7.2"
    container_name: "bookshop-redis"
    ports:
      - 6379:6379

  bookshop-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: bookshop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  bookshop-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: "bookshop-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
    ports:
      - 8080:8080
