apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Tempo
  - name: Loki

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-bookshop-vitale
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
  - name: Tempo
    type: tempo
    uid: tempo-bookshop-vitale
    access: proxy
    orgId: 1
    url: http://tempo:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki-bookshop-vitale'
        tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
        mappedTags: [ { key: 'service.name', value: 'application' }  ]
        mapTagNamesEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      lokiSearch:
        datasourceUid: 'loki-bookshop-vitale'
      serviceMap:
        datasourceUid: 'prometheus-bookshop-vitale'
      search:
        hide: false
      nodeGraph:
        enabled: true
  - name: Loki
    type: loki
    uid: loki-bookshop-vitale
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo-bookshop-vitale
          matcherRegex: \[.+,(.+?),
          name: TraceID
          url: $${__value.raw}
